spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jtjdb
    username: jtj
    password: jtjPass
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true